# Generated by Django 2.1.5 on 2019-07-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
